providers = ["python"]

[phases.setup]
# System packages required for OCR of scanned PDFs
# poppler_utils provides the `pdftoppm` binary used by pdf2image
# tesseract provides the OCR engine used by pytesseract
# Also install Python explicitly to avoid "python: command not found" during build
nixPkgs = ["poppler_utils", "tesseract", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]


